services:
  epub-optimizer:
    container_name: epub-optimizer
    image: ghcr.io/henrybaby/epub-optimizer:latest
    restart: unless-stopped
    ports:
      - "4200:4200"
    environment:
      EPUB_OPTIMIZER_MAX_UPLOAD_MB: "100"
    volumes:
      - epubo_data:/data
      - epubo_watch:/watch
      - epubo_output:/output

volumes:
  epubo_data:
    name: epubo_data
  epubo_watch:
    name: epubo_watch
  epubo_output:
    name: epubo_output
